# Generated by Django 6.1.1 on 2026-09-18 21:57

import django.core.validators
import django.db.models.deletion
import payments.storage
import sales.validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('BANK_TRANSFER', 'Transferencia bancaria')], max_length=20, verbose_name='método de pago')),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], max_length=20, verbose_name='estado del pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe')),
                ('currency', models.CharField(default='ARS', max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe tener exactamente tres letras mayúsculas.', regex='\\A[A-Z]{3}\\Z')], verbose_name='moneda')),
                ('voucher', models.FileField(blank=True, null=True, storage=payments.storage.get_voucher_storage, upload_to=payments.storage.voucher_upload_path, verbose_name='comprobante')),
                ('reference', models.CharField(blank=True, default='', max_length=255, verbose_name='referencia o notas')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha de revisión')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='motivo de rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.booking', verbose_name='reserva')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'method'], name='payments_status_method_idx'), models.Index(fields=['created_at'], name='payments_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['UNDER_REVIEW', 'APPROVED'])), fields=('booking',), name='payments_active_booking_unique', violation_error_message='Ya existe un pago en revisión o aprobado para esta reserva.'), models.CheckConstraint(condition=models.Q(('method__in', ['CASH', 'BANK_TRANSFER'])), name='payments_method_valid', violation_error_message='El método de pago no es válido.'), models.CheckConstraint(condition=models.Q(('status__in', ['UNDER_REVIEW', 'APPROVED', 'REJECTED'])), name='payments_status_valid', violation_error_message='El estado del pago no es válido.'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payments_amount_positive', violation_error_message='El importe del pago debe ser mayor que cero.')],
            },
        ),
    ]
