# Generated by Django 6.0.2 on 2026-09-19 06:33

import django.db.models.deletion
import sales.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_active_booking_unique',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payments_status_valid',
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_deadline_at',
            field=models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='límite para subir comprobante'),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_deadline_at',
            field=models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='límite de revisión'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('AWAITING_VOUCHER', 'Esperando comprobante'), ('UNDER_REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('EXPIRED', 'Expirado')], max_length=20, verbose_name='estado del pago'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['AWAITING_VOUCHER', 'UNDER_REVIEW', 'APPROVED'])), fields=('booking',), name='payments_active_booking_unique', violation_error_message='Ya existe un pago en revisión o aprobado para esta reserva.'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AWAITING_VOUCHER', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED'])), name='payments_status_valid', violation_error_message='El estado del pago no es válido.'),
        ),
    ]
