# Generated by Django 6.1.1 on 2026-09-03 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('layout_asientos', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='core.ruta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='core.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.CharField(max_length=20)),
                ('pasajero_nombre', models.CharField(max_length=255)),
                ('pasajero_dni', models.CharField(max_length=50)),
                ('parada_bajada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajadas', to='core.parada')),
                ('parada_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subidas', to='core.parada')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.reserva')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_items', to='core.salida')),
            ],
        ),
    ]
