# Generated by Django 6.1.1 on 2026-09-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='parada_subida',
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='parada_bajada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reservaitem',
            name='salida',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='ruta',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Parada',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='ReservaItem',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
