# Generated by Django 6.0.2 on 2026-10-07 19:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_public_transfer_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_note', models.CharField(blank=True, default='', max_length=255)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('OPENING', 'Apertura'), ('CASH_SALE', 'Cobro en efectivo'), ('ADJUSTMENT_IN', 'Ingreso manual'), ('ADJUSTMENT_OUT', 'Egreso manual')], max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movement', to='payments.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cash_register.cashsession')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='cash_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'OPEN'), models.Q(('closed_by__isnull', False), ('closed_at__isnull', False), ('closing_amount__isnull', False)), _connector='OR'), name='cash_closed_fields_required'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='cash_only_one_open_session'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['OPENING', 'CASH_SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT'])), name='cash_movement_kind_valid'),
        ),
    ]
