# Generated by Django 6.0.2 on 2026-10-07 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0002_alter_cashmovement_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashsession',
            name='cash_only_one_open_session',
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('opened_by',), name='cash_one_open_session_per_operator'),
        ),
    ]
