# Generated by Django 6.1.1 on 2026-09-08 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Edición'), ('ACTIVATE', 'Activación'), ('DEACTIVATE', 'Desactivación')], max_length=10, verbose_name='acción')),
                ('entity_type', models.CharField(max_length=100, verbose_name='tipo de entidad')),
                ('entity_id', models.CharField(max_length=64, verbose_name='identificador de entidad')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('before', models.JSONField(default=dict, verbose_name='datos anteriores')),
                ('after', models.JSONField(default=dict, verbose_name='datos posteriores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario actor')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
