# Generated by Django on 2026-09-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('normalized_email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='correo normalizado')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='teléfono')),
                ('google_sub', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='identificador de Google')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('COMMERCIAL_COMMUNICATIONS', 'Comunicaciones comerciales y promociones'), ('PRIVACY_POLICY', 'Política de privacidad')], default='COMMERCIAL_COMMUNICATIONS', max_length=50, verbose_name='tipo de consentimiento')),
                ('granted', models.BooleanField(default=False, verbose_name='otorgado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='agente de usuario')),
                ('version', models.CharField(default='v1.0', max_length=20, verbose_name='versión del texto')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'registro de consentimiento',
                'verbose_name_plural': 'registros de consentimiento',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de asociación')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_booking', to='sales.booking', verbose_name='reserva')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'reserva de cliente',
                'verbose_name_plural': 'reservas de clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingClaimToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='hash del token de reclamo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de reclamo')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_token', to='sales.booking', verbose_name='reserva')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tokens', to='customers.customer', verbose_name='reclamado por')),
            ],
            options={
                'verbose_name': 'token de reclamo de reserva',
                'verbose_name_plural': 'tokens de reclamo de reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
