# Generated by Django 6.0.2 on 2026-09-21 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingclaimtoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='customerconsent',
            name='origin',
            field=models.CharField(default='web', max_length=50, verbose_name='origen'),
        ),
    ]
