# Generated by Django 6.1.1 on 2026-09-08 00:11

import django.core.validators
import django.db.models.deletion
import operations.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usá letras mayúsculas y números, separados opcionalmente por guiones.', regex='\\A[A-Z0-9]+(?:-[A-Z0-9]+)*\\Z')], verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'recorrido',
                'verbose_name_plural': 'recorridos',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Usá letras mayúsculas y números, separados opcionalmente por guiones.', regex='\\A[A-Z0-9]+(?:-[A-Z0-9]+)*\\Z')], verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('city', models.CharField(max_length=150, verbose_name='ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usá letras mayúsculas y números, separados opcionalmente por guiones.', regex='\\A[A-Z0-9]+(?:-[A-Z0-9]+)*\\Z')], verbose_name='código interno')),
                ('display_name', models.CharField(max_length=150, verbose_name='nombre visible')),
                ('license_plate', models.CharField(blank=True, default='', max_length=20, verbose_name='patente')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'colectivo',
                'verbose_name_plural': 'colectivos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('license_plate', ''), _negated=True), fields=('license_plate',), name='ops_bus_plate_unique', violation_error_message='La patente ya está asignada a otro colectivo.')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('departure_at', models.DateTimeField(validators=[operations.validators.validate_aware_datetime], verbose_name='salida')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('BOARDING', 'En embarque'), ('STARTED', 'Iniciado'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=9, verbose_name='estado')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.bus', verbose_name='colectivo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='operations.route', verbose_name='recorrido')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='orden')),
                ('scheduled_at', models.DateTimeField(validators=[operations.validators.validate_aware_datetime], verbose_name='horario programado')),
                ('allows_boarding', models.BooleanField(verbose_name='permite subir')),
                ('allows_alighting', models.BooleanField(verbose_name='permite bajar')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='operations.stop', verbose_name='parada')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='operations.trip', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'parada del viaje',
                'verbose_name_plural': 'paradas del viaje',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='TripFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('seat_category', models.CharField(choices=[('SEMI_CAMA', 'Semicama'), ('CAMA', 'Cama')], max_length=9, verbose_name='categoría')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe')),
                ('currency', models.CharField(default='ARS', max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe tener exactamente tres letras mayúsculas.', regex='\\A[A-Z]{3}\\Z')], verbose_name='moneda')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='operations.trip', verbose_name='viaje')),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_fares', to='operations.tripstop', verbose_name='destino')),
                ('origin_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_fares', to='operations.tripstop', verbose_name='origen')),
            ],
            options={
                'verbose_name': 'tarifa del viaje',
                'verbose_name_plural': 'tarifas del viaje',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('deck', models.CharField(choices=[('UPPER', 'Planta alta'), ('LOWER', 'Planta baja')], max_length=5, verbose_name='planta')),
                ('category', models.CharField(choices=[('SEMI_CAMA', 'Semicama'), ('CAMA', 'Cama')], max_length=9, verbose_name='categoría')),
                ('position_x', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='posición horizontal')),
                ('position_y', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='posición vertical')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='operations.bus', verbose_name='colectivo')),
            ],
            options={
                'verbose_name': 'butaca',
                'verbose_name_plural': 'butacas',
                'constraints': [models.UniqueConstraint(fields=('bus', 'number'), name='ops_seat_number_unique', violation_error_message='El número de butaca ya existe en el colectivo.'), models.UniqueConstraint(fields=('bus', 'deck', 'position_x', 'position_y'), name='ops_seat_position_unique', violation_error_message='La posición ya está ocupada en esa planta.'), models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='ops_seat_number_positive', violation_error_message='El número de butaca debe ser mayor o igual a 1.'), models.CheckConstraint(condition=models.Q(('position_x__gte', 0), ('position_y__gte', 0)), name='ops_seat_position_nonnegative', violation_error_message='Las coordenadas deben ser mayores o iguales a 0.'), models.CheckConstraint(condition=models.Q(('deck__in', ['UPPER', 'LOWER'])), name='ops_seat_deck_valid', violation_error_message='La planta no es válida.'), models.CheckConstraint(condition=models.Q(('category__in', ['SEMI_CAMA', 'CAMA'])), name='ops_seat_category_valid', violation_error_message='La categoría no es válida.')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='orden')),
                ('allows_boarding', models.BooleanField(verbose_name='permite subir')),
                ('allows_alighting', models.BooleanField(verbose_name='permite bajar')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='operations.route', verbose_name='recorrido')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='operations.stop', verbose_name='parada')),
            ],
            options={
                'verbose_name': 'parada del recorrido',
                'verbose_name_plural': 'paradas del recorrido',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence'), name='ops_route_sequence_unique', violation_error_message='El orden ya existe en el recorrido.'), models.UniqueConstraint(fields=('route', 'stop'), name='ops_route_stop_unique', violation_error_message='La parada ya existe en el recorrido.'), models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='ops_route_sequence_positive', violation_error_message='El orden debe ser mayor o igual a 1.'), models.CheckConstraint(condition=models.Q(('allows_boarding', True), ('allows_alighting', True), _connector='OR'), name='ops_route_stop_permission', violation_error_message='La parada debe permitir subir o bajar.')],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'BOARDING', 'STARTED', 'COMPLETED', 'CANCELLED'])), name='ops_trip_status_valid', violation_error_message='El estado del viaje no es válido.'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence'), name='ops_trip_sequence_unique', violation_error_message='El orden ya existe en el viaje.'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'stop'), name='ops_trip_stop_unique', violation_error_message='La parada ya existe en el viaje.'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='ops_trip_sequence_positive', violation_error_message='El orden debe ser mayor o igual a 1.'),
        ),
        migrations.AddConstraint(
            model_name='tripfare',
            constraint=models.UniqueConstraint(fields=('trip', 'origin_stop', 'destination_stop', 'seat_category'), name='ops_fare_segment_unique', violation_error_message='Ya existe una tarifa para ese viaje, tramo y categoría.'),
        ),
        migrations.AddConstraint(
            model_name='tripfare',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ops_fare_amount_positive', violation_error_message='El importe debe ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='tripfare',
            constraint=models.CheckConstraint(condition=models.Q(('origin_stop', models.F('destination_stop')), _negated=True), name='ops_fare_distinct_stops', violation_error_message='El origen y el destino deben ser diferentes.'),
        ),
        migrations.AddConstraint(
            model_name='tripfare',
            constraint=models.CheckConstraint(condition=models.Q(('seat_category__in', ['SEMI_CAMA', 'CAMA'])), name='ops_fare_category_valid', violation_error_message='La categoría no es válida.'),
        ),
    ]
