# Generated by Django 6.0.2 on 2026-10-01 21:15

import operations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, validators=[operations.validators.validate_aware_datetime], verbose_name='fecha de finalización'),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, validators=[operations.validators.validate_aware_datetime], verbose_name='fecha de inicio'),
        ),
    ]
