# Generated by Django 6.0.2 on 2026-09-19 07:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sales.validators
import tickets.storage
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('ticket_code', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='código legible de pasaje')),
                ('verification_token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='hash del token de verificación QR')),
                ('download_token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='hash del token de descarga')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ISSUED', 'Emitido'), ('VOID', 'Anulado')], default='PENDING', max_length=15, verbose_name='estado del pasaje')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=tickets.storage.get_ticket_storage, upload_to=tickets.storage.ticket_upload_path, verbose_name='archivo PDF')),
                ('pdf_path', models.CharField(blank=True, default='', max_length=255, verbose_name='ruta PDF privada')),
                ('issued_at', models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha de emisión')),
                ('voided_at', models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha de anulación')),
                ('void_reason', models.TextField(blank=True, default='', verbose_name='motivo de anulación')),
                ('passenger_name', models.CharField(max_length=255, verbose_name='nombre completo')),
                ('passenger_document_masked', models.CharField(max_length=50, verbose_name='documento enmascarado')),
                ('origin_stop_name', models.CharField(max_length=150, verbose_name='parada de subida')),
                ('destination_stop_name', models.CharField(max_length=150, verbose_name='parada de bajada')),
                ('departure_at', models.DateTimeField(validators=[sales.validators.validate_aware_datetime], verbose_name='horario de subida')),
                ('arrival_at', models.DateTimeField(validators=[sales.validators.validate_aware_datetime], verbose_name='horario de bajada')),
                ('seat_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de butaca')),
                ('seat_category', models.CharField(max_length=20, verbose_name='categoría de butaca')),
                ('seat_category_display', models.CharField(max_length=50, verbose_name='descripción de categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio histórico')),
                ('currency', models.CharField(default='ARS', max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe tener exactamente tres letras mayúsculas.', regex='\\A[A-Z]{3}\\Z')], verbose_name='moneda')),
                ('booking_public_id', models.UUIDField(db_index=True, verbose_name='código de reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sales.booking', verbose_name='reserva')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sales.bookingleg', verbose_name='tramo')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sales.bookingpassenger', verbose_name='pasajero')),
                ('seat_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='sales.seatassignment', verbose_name='asignación de butaca')),
            ],
            options={
                'verbose_name': 'pasaje',
                'verbose_name_plural': 'pasajes',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ISSUE', 'Emisión'), ('DOWNLOAD', 'Descarga'), ('VOID', 'Anulación'), ('EMAIL', 'Envío de correo'), ('VERIFY', 'Verificación')], max_length=20, verbose_name='acción')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('metadata', models.JSONField(default=dict, verbose_name='metadatos sin PII')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario actor')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_events', to='sales.booking', verbose_name='reserva')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='tickets.ticket', verbose_name='pasaje')),
            ],
            options={
                'verbose_name': 'evento de auditoría de pasajes',
                'verbose_name_plural': 'eventos de auditoría de pasajes',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TicketEmailAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=15, verbose_name='estado del intento')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='correo destinatario')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de intento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('error_message', models.CharField(blank=True, default='', max_length=255, verbose_name='mensaje de error sanitizado')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_email_attempts', to='sales.booking', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'intento de envío de pasajes',
                'verbose_name_plural': 'intentos de envío de pasajes',
                'ordering': ['-attempted_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tk_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('booking', 'leg', 'passenger'), name='tickets_ticket_booking_leg_pax_unique', violation_error_message='Ya existe un pasaje para este pasajero en este tramo de la reserva.'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('leg', 'passenger'), name='tickets_ticket_leg_pax_unique', violation_error_message='El pasajero ya tiene un pasaje emitido en este tramo.'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('seat_assignment',), name='tickets_ticket_seat_assignment_unique', violation_error_message='Esta asignación de butaca ya posee un pasaje asociado.'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ISSUED', 'VOID'])), name='tickets_ticket_status_valid', violation_error_message='El estado del pasaje no es válido.'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', Decimal('0.00'))), name='tickets_ticket_price_positive', violation_error_message='El precio del pasaje debe ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gte', 1)), name='tickets_ticket_seat_num_positive', violation_error_message='El número de butaca debe ser mayor o igual a 1.'),
        ),
        migrations.AddIndex(
            model_name='ticketauditevent',
            index=models.Index(fields=['action', 'created_at'], name='tickets_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketemailattempt',
            index=models.Index(fields=['booking', 'status'], name='tickets_email_bk_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketemailattempt',
            index=models.Index(fields=['attempted_at'], name='tickets_email_attempt_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketemailattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SENT', 'FAILED'])), name='tickets_attempt_status_valid', violation_error_message='El estado del intento de envío no es válido.'),
        ),
    ]
