# Generated by Django 6.1.1 on 2026-09-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('SUCCEEDED', 'Emitido'), ('FAILED', 'Fallido')], default='PENDING', max_length=15, verbose_name='estado de emisión')),
                ('email_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=15, verbose_name='estado de correo')),
                ('issue_error', models.CharField(blank=True, default='', max_length=255, verbose_name='error de emisión')),
                ('email_error', models.CharField(blank=True, default='', max_length=255, verbose_name='error de correo')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='intentos')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='último intento')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_fulfillment', to='sales.booking', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'trabajo de entrega de pasajes',
                'verbose_name_plural': 'trabajos de entrega de pasajes',
                'indexes': [models.Index(fields=['issue_status', 'email_status'], name='tickets_fulfill_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('issue_status__in', ['PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED'])), name='tickets_fulfillment_issue_status_valid'), models.CheckConstraint(condition=models.Q(('email_status__in', ['PENDING', 'SENT', 'FAILED'])), name='tickets_fulfillment_email_status_valid')],
            },
        ),
    ]
