# Generated by Django 6.0.2 on 2026-09-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        ('tickets', '0002_ticketfulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfulfillment',
            name='lease_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bloqueo de procesamiento hasta'),
        ),
        migrations.AddField(
            model_name='ticketfulfillment',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='próximo intento permitido'),
        ),
        migrations.AddIndex(
            model_name='ticketfulfillment',
            index=models.Index(fields=['next_attempt_at', 'updated_at'], name='tickets_fulfill_retry_idx'),
        ),
    ]
