# Generated by Django 6.0.2 on 2026-10-01 21:13

import django.db.models.deletion
import django.utils.timezone
import sales.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
        ('tickets', '0003_ticketfulfillment_lease_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketauditevent',
            name='action',
            field=models.CharField(choices=[('ISSUE', 'Emisión'), ('DOWNLOAD', 'Descarga'), ('VOID', 'Anulación'), ('EMAIL', 'Envío de correo'), ('VERIFY', 'Verificación'), ('BOARDING', 'Embarque'), ('BOARDING_REVERSAL', 'Reversión de embarque')], max_length=20, verbose_name='acción'),
        ),
        migrations.CreateModel(
            name='BoardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarded_at', models.DateTimeField(default=django.utils.timezone.now, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha y hora de embarque')),
                ('status', models.CharField(choices=[('ACTIVE', 'Embarcado'), ('REVERSED', 'Revertido')], default='ACTIVE', max_length=10, verbose_name='estado del registro')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha y hora de reversión')),
                ('reversal_reason', models.TextField(blank=True, default='', verbose_name='motivo de reversión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='sales.bookingpassenger', verbose_name='pasajero')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_boarding_records', to=settings.AUTH_USER_MODEL, verbose_name='usuario que revirtió')),
                ('seat_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='sales.seatassignment', verbose_name='asignación de butaca')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='tickets.ticket', verbose_name='pasaje')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='operations.trip', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'registro de embarque',
                'verbose_name_plural': 'registros de embarque',
                'ordering': ['-boarded_at', '-pk'],
                'indexes': [models.Index(fields=['trip', 'status'], name='tickets_boarding_trip_status_idx'), models.Index(fields=['operator', 'boarded_at'], name='tickets_boarding_operator_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('ticket',), name='tickets_active_boarding_ticket_unique', violation_error_message='El pasaje ya tiene un embarque activo.'), models.CheckConstraint(condition=models.Q(('status__in', ['ACTIVE', 'REVERSED'])), name='tickets_boarding_status_valid', violation_error_message='El estado del embarque no es válido.'), models.CheckConstraint(condition=models.Q(models.Q(('reversed_at__isnull', True), ('status', 'ACTIVE')), models.Q(('reversed_at__isnull', False), ('status', 'REVERSED')), _connector='OR'), name='tickets_boarding_reversal_consistent', violation_error_message='La reversión del embarque no es consistente.')],
            },
        ),
    ]
