# Generated by Django 6.0.2 on 2026-10-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticketauditevent_action_boardingrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='boardingrecord',
            new_name='tickets_board_trip_idx',
            old_name='tickets_boarding_trip_status_idx',
        ),
        migrations.RenameIndex(
            model_name='boardingrecord',
            new_name='tickets_board_op_idx',
            old_name='tickets_boarding_operator_idx',
        ),
    ]
