# Generated by Django 6.0.2 on 2026-10-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BOOKING_HELD', 'Reserva creada'), ('TRANSFER_STARTED', 'Transferencia iniciada'), ('VOUCHER_RECEIVED', 'Comprobante recibido'), ('TRANSFER_APPROVED', 'Transferencia aprobada'), ('TRANSFER_REJECTED', 'Transferencia rechazada'), ('BOOKING_EXPIRED', 'Reserva vencida'), ('MANUAL_BOOKING_CONFIRMED', 'Reserva manual confirmada')], max_length=40)),
                ('event_key', models.CharField(max_length=120)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'En proceso'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactional_notifications', to='sales.booking')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notif_status_next_idx'), models.Index(fields=['booking', 'status'], name='notif_booking_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_key', 'notification_type', 'recipient_email'), name='notifications_event_recipient_type_unique')],
            },
        ),
    ]
