# Generated by Django 6.0.2 on 2026-10-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('sales', '0002_bookingpassenger_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionalnotification',
            name='notifications_event_recipient_type_unique',
        ),
        migrations.AddConstraint(
            model_name='transactionalnotification',
            constraint=models.UniqueConstraint(fields=('booking', 'event_key', 'notification_type', 'recipient_email'), name='notifications_event_recipient_type_unique'),
        ),
    ]
