# Generated by Django 6.1.1 on 2026-09-17 05:49

import django.core.validators
import django.db.models.deletion
import sales.validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='identificador público')),
                ('channel', models.CharField(choices=[('ONLINE', 'Online'), ('MANUAL', 'Manual')], max_length=10, verbose_name='canal')),
                ('status', models.CharField(choices=[('HELD', 'Retenida'), ('CONFIRMED', 'Confirmada'), ('EXPIRED', 'Expirada'), ('RELEASED', 'Liberada')], default='HELD', max_length=10, verbose_name='estado')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='teléfono')),
                ('expires_at', models.DateTimeField(validators=[sales.validators.validate_aware_datetime], verbose_name='fecha de vencimiento')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, validators=[sales.validators.validate_aware_datetime], verbose_name='fecha de confirmación')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('sequence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='secuencia')),
                ('origin_stop_name', models.CharField(max_length=150, verbose_name='nombre de parada de subida')),
                ('destination_stop_name', models.CharField(max_length=150, verbose_name='nombre de parada de bajada')),
                ('departure_at', models.DateTimeField(validators=[sales.validators.validate_aware_datetime], verbose_name='horario de subida')),
                ('arrival_at', models.DateTimeField(validators=[sales.validators.validate_aware_datetime], verbose_name='horario de bajada')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legs', to='sales.booking', verbose_name='reserva')),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_booking_legs', to='operations.tripstop', verbose_name='parada de bajada')),
                ('origin_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_booking_legs', to='operations.tripstop', verbose_name='parada de subida')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_legs', to='operations.trip', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'tramo de reserva',
                'verbose_name_plural': 'tramos de reserva',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='posición')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='sales.booking', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'pasajero de reserva',
                'verbose_name_plural': 'pasajeros de reserva',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('status', models.CharField(choices=[('HELD', 'Retenida'), ('CONFIRMED', 'Confirmada'), ('RELEASED', 'Liberada')], default='HELD', max_length=10, verbose_name='estado')),
                ('seat_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de butaca')),
                ('category', models.CharField(choices=[('SEMI_CAMA', 'Semicama'), ('CAMA', 'Cama')], max_length=9, verbose_name='categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio')),
                ('currency', models.CharField(default='ARS', max_length=3, validators=[django.core.validators.RegexValidator(message='La moneda debe tener exactamente tres letras mayúsculas.', regex='\\A[A-Z]{3}\\Z')], verbose_name='moneda')),
                ('leg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='sales.bookingleg', verbose_name='tramo')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='sales.bookingpassenger', verbose_name='pasajero')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='operations.seat', verbose_name='butaca')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_assignments', to='operations.trip', verbose_name='viaje')),
            ],
            options={
                'verbose_name': 'asignación de butaca',
                'verbose_name_plural': 'asignaciones de butaca',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='sales_bk_status_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='sales_bk_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['ONLINE', 'MANUAL'])), name='sales_booking_channel_valid', violation_error_message='El canal de venta no es válido.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['HELD', 'CONFIRMED', 'EXPIRED', 'RELEASED'])), name='sales_booking_status_valid', violation_error_message='El estado de la reserva no es válido.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('channel', 'MANUAL'), ('seller__isnull', True), _connector='OR'), name='sales_booking_seller_only_manual', violation_error_message='Las reservas online no pueden tener vendedor asignado.'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), ('confirmed_at__isnull', False), _connector='OR'), name='sales_booking_confirmed_at_required', violation_error_message='Las reservas confirmadas deben registrar fecha de confirmación.'),
        ),
        migrations.AddConstraint(
            model_name='bookingleg',
            constraint=models.UniqueConstraint(fields=('booking', 'sequence'), name='sales_leg_booking_seq_unique', violation_error_message='El orden del tramo ya existe en la reserva.'),
        ),
        migrations.AddConstraint(
            model_name='bookingleg',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__in', [1, 2])), name='sales_leg_sequence_valid', violation_error_message='La secuencia del tramo debe ser 1 o 2.'),
        ),
        migrations.AddConstraint(
            model_name='bookingleg',
            constraint=models.CheckConstraint(condition=models.Q(('origin_stop', models.F('destination_stop')), _negated=True), name='sales_leg_distinct_stops', violation_error_message='La parada de subida y bajada deben ser diferentes.'),
        ),
        migrations.AddConstraint(
            model_name='bookingpassenger',
            constraint=models.UniqueConstraint(fields=('booking', 'position'), name='sales_passenger_booking_pos_unique', violation_error_message='La posición del pasajero ya existe en la reserva.'),
        ),
        migrations.AddConstraint(
            model_name='bookingpassenger',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='sales_passenger_pos_positive', violation_error_message='La posición del pasajero debe ser mayor o igual a 1.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(fields=('leg', 'passenger'), name='sales_assignment_leg_passenger_unique', violation_error_message='El pasajero ya tiene una butaca asignada en este tramo.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['HELD', 'CONFIRMED'])), fields=('trip', 'seat'), name='sales_active_trip_seat_unique', violation_error_message='La butaca ya está ocupada o retenida en este viaje.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['HELD', 'CONFIRMED', 'RELEASED'])), name='sales_assignment_status_valid', violation_error_message='El estado de la asignación no es válido.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='sales_assignment_price_positive', violation_error_message='El precio debe ser mayor que cero.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.CheckConstraint(condition=models.Q(('seat_number__gte', 1)), name='sales_assignment_seat_num_positive', violation_error_message='El número de butaca debe ser mayor o igual a 1.'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['SEMI_CAMA', 'CAMA'])), name='sales_assignment_category_valid', violation_error_message='La categoría de butaca no es válida.'),
        ),
    ]
