# Generated by Django 6.1.1 on 2026-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpassenger',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='número de documento'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='document_type',
            field=models.CharField(blank=True, default='DNI', max_length=20, verbose_name='tipo de documento'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='nombre'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='género'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='apellido'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='nationality',
            field=models.CharField(blank=True, default='Argentina', max_length=50, verbose_name='nacionalidad'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='normalized_document',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='documento normalizado'),
        ),
    ]
